stages:
  - CheckESLint

.ESLintScan: &ESLintScan |
  pushComment(){
      curl --request POST --header "PRIVATE-TOKEN: $USER_TOKEN" \
      --form "note=$OUTPUT" --form "path=dudeism.md" \
      --form "line=1" --form "line_type=new" \
      https://git.hblab.vn/api/v4/projects/$CI_PROJECT_ID/repository/commits/$CI_COMMIT_SHA/comments
      echo $OUTPUT
      exit 1
  }
  
  OUTPUT=$(npm run eslint 2>&1) || pushComment
  
ESLint:
  stage: CheckESLint
  image: node:10.11.0-alpine
  script:
    - apk add curl
    - npm install
    - *ESLintScan
