export const HOME_FETCH_INDEX = 'HOME_FETCH_INDEX';
export const HOME_SET_INDEX = 'HOME_SET_INDEX';
export const HOME_FETCH_CHART = 'HOME_FETCH_CHART';
export const HOME_SET_CHART = 'HOME_SET_CHART';
